# Code from red hat ai course ai267

In [ ]:
%pip install -U numpy
%pip install -U scikit-learn


In [4]:
import numpy as np
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
data



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
data.shape


(3, 3)

In [7]:
data > 5


array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [8]:
data ** 3


array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [9]:
data[::-1]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [10]:
data


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
data[::-1][::-1]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
data[0:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
data[:,1:]


array([[2, 3],
       [5, 6],
       [8, 9]])

In [15]:
data[:,:-1]


array([[1, 2],
       [4, 5],
       [7, 8]])